services:
  angular-app:
    image: node:16
    container_name: angular-app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    command: >
      sh -c "npm install && npm start"