version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    networks:
      - hao123_network

networks:
  hao123_network:
    driver: bridge
